version: '3.7'
services:
  # Qdrant - commented out, using cloud instance
  # Uncomment below for local development
  # qdrant:
  #   image: qdrant/qdrant
  #   ports:
  #     - "6333:6333"
  #     - "6334:6334"
  #   volumes:
  #     - ./qdrant_storage:/qdrant/storage
  #   restart: unless-stopped
    web:
      build: .
      env_file:
        - ../.env